# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oX9yaqNmMVfIN49w98sUHYTEPWyE4c-h
"""

import json
import requests


#customer_journeys = 
with open(r"/content/customer_journeys_sample.json") as jsonFile:
  jsonObject = json.load(jsonFile)

redistribution_parameter = {
    'initializer' : {
        'direction' : 'earlier_sessions_only',
        'receive_threshold' : 0,
        'redistribution_channel_labels' : ['Direct', 'Email_Newsletter'],
    },
    'holder' : {
        'direction' : 'any_session',
        'receive_threshold' : 0,
        'redistribution_channel_labels' : ['Direct', 'Email_Newsletter'],
    },
    'closer' : {
        'direction' : 'later_sessions_only',
        'receive_threshold' : 0.1,
        'redistribution_channel_labels' : ['SEO - Brand'],
    }
}

## Insert API Key here
api_key = 'afab1b42-ab3d-4563-9cc5-c2e7bba9d120'

## Insert Conversion Type ID here
conv_type_id = 'new and returning customers'

api_url = "https://api.ihc-attribution.com/v1/compute_ihc?conv_type_id={conv_type_id}".format(conv_type_id = conv_type_id)

body = {
    'customer_journeys': jsonObject 
}

response = requests.post(
        api_url, 
        data=json.dumps(body), 
        headers= {
            'Content-Type': 'application/json',    
            'x-api-key': api_key
        }
    )

results = response.json()
#print(results)
print(f"Status Code: {results['statusCode']}")

print("-"*30)

print(f"Partial Failure Errors: {results['partialFailureErrors']}")

print("-"*30)

display(results['value'])



ls